FROM resin/rpi-raspbian:jessie

RUN apt-get -y update
RUN apt-get -y install curl

CMD while echo $(curl --silent --request POST --data "" http://$BRAIN_HOST/api/heartbeat); do sleep ${HEARTBEAT_INTERVAL_IN_SECONDS:-60}; done
